### ISSUE TITLE
Unify headers

### ISSUE THREAD

**Issue by MariiaBubley** [d33pspace/RenewalMgtApp-Html#24]
@d33pspace I thought that the screens should be fixed in height and scroll inside a fixed container. Also, all headers can be fixed on the page, so the application will look neater.

Now
https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html#

My proposal:
https://drive.google.com/file/d/1CCcHQ_OjWfLYc9BtTCYmj4gKW71HAJXe/view?usp=sharing

@d33pspace What do you think?

**Comment by d33pspace** [comment]
@MariiaBubley I see. Your proposal is nice. This demonstrates a header fixed on the page. 

Questions:

(1) Are headers on all pages the same height? 
(2) I do not know what you mean by "screens should be fixed in height and scroll inside a fixed container." Can you demonstrate please?

**Comment by MariiaBubley** [comment]
@d33pspace 
(1) Examples of header you can see here
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1703%3A37415

Ps. I also changed some headers (made only two variants, except main) for unifying the app, I made comments in Figma.

(2) I meant the same, If the header will be fixed, the content will be scrolling inside the container. I put it wrong with formulating in the previous comment.

**Comment by d33pspace** [comment]
@AnKar112 @academws Mariia has made edits to the headers in some of the Figma models. Comments have been added to updated models. 

All headers should be fixed on the page.

**Comment by AnKar112** [comment]
unfulfilled request, items we trashed, edit item, Operation report, Distribution report - what the page is it?
All other pages done

**Comment by d33pspace** [comment]
Hi @AnKar112 @academws I apologize for the changes on the headers, but let's please fix them carefully. It's important to me. 😊

(1) main_page and main_page with burger opened seem to have two different header heights. They are the same in the Figma models.

(2) users_list header seems different than guest_list and start_the_service. I don't know which one is correct, but users_list is slightly different than the other two. As for item_catalogue, it will actually belong to the next group because I want to remove the search from it. Also, some elements should also be unified with the rest of the pages, such as height, header text, and back arrow.

(3) There seem to be several different varieties of headings on the following pages, they should all be unified. Again, I do not know which is correct if any, but I see five styles of headings here (a-e) please unify all. 

new_guest (a)
edit_guest (a)
edit_user_profile (b)
settings (c)
settings_language (c)
settings_notifications (c)
settings_service (c)
new_item (d)
reports_main (e)
reports_operations (e)

(4) return_page, take_page and give_page have unified headings, but some elements should also be unified with the rest of the pages, such as height, header text and back arrow.

(5) Also, I noticed that because of the container on both sides, the scroll bar is partially covered by the header. Can we fix it so the scroll bar is only on the page below the header?

**Comment by AnKar112** [comment]
1 - did we need page burger_opened at all?
2 - I didn't get. In some tasks you ask to remove search from Item Catalogue, in this https://github.com/d33pspace/RenewalMgtApp-Html/issues/23 - to add
3, 4, 5 - check it now, please
6 - can you give me screenshot? 
7 - as I asked before, F5 help with this? If no, give me your resolution please
8 - what mean 16% ? I asked before send box-shadow in pixels, check my message here https://github.com/d33pspace/RenewalMgtApp-Html/issues/5#issuecomment-922070864

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Beautiful work, Anton, thank you! Just a few minor things...

(1) I do not think burger_opened is necessary because burger menu on main_page is functional. However, please note that the line below the burger menu header should be at the same place as the bottom of the main_page (see illustration from Figma here). Please make this change.
![Screenshot 2021-09-20 161000](https://user-images.githubusercontent.com/13606352/133973058-0a083135-31d6-4a7b-bcb1-1347378dba93.png)

(2) I'm sorry about the confusion. Please remove the search bar from item_catalogue and unify the header with settings (for example).

(3) On the following three pages, when you scroll down and the shadow below the header appears, the shadow is slightly lower than on the other pages: guest_profile_behavior, guest_profile_history, guest_profile_items_lost. (Compare with settings, for example.)

(4) Perfect! 

(5) The back arrow in the upper left corner of user_profile and guest_profile are in a different position than the rest of the pages, (for example, edit_user_profile). Please unify these pages.

@MariiaBubley 
Note the header is slightly taller on these two pages to accommodate the date range. I think this is fine. Can you comment?
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_operations.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html

For an example, compare with: (header on most pages like this)
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_main.html

Also, header is not fixed on:
https://d33pspace.github.io/RenewalMgtApp-Html/app/user_profile.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile.html
Is this acceptable?

Finally, there is no shadow below the header on:
https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html
But this seems fine since the header is black. Can you confirm?

**Comment by MariiaBubley** [comment]
@d33pspace @AnKar112 
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html
Please, check on mockup - pudding before the first title have to be 24px (this block was moved up before).

Please, add titles on these pages as well.
https://d33pspace.github.io/RenewalMgtApp-Html/app/user_profile.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile.html

Other pages are fine!

**Comment by d33pspace** [comment]
@MariiaBubley 
What do you mean add titles to user_profile and guest_profile? It looks like in Figma these pages also do not have titles. (?)

@AnKar112 @academws 
Based on Mariia's feedback above, please add to my list...

(6) Adjust the headers on reports_operations and reports_behavior to comply with the style in Figma. To me the most obvious problem is the date selection link is too close to the content below it.
![Screenshot 2021-09-21 144314](https://user-images.githubusercontent.com/13606352/134124026-d2441366-dc42-4dc4-a056-d763c120c171.png)

**Comment by AnKar112** [comment]
(1) I do not think burger_opened is necessary because burger menu on main_page is functional. However, please note that the line below the burger menu header should be at the same place as the bottom of the main_page (see illustration from Figma here). Please make this change. - them wasn't in mockup) http://ipic.su/img/img7/fs/kiss_57kb.1632249681.png
**Fixed**

Btw, I find out that file main_page_admin wasn't in links list. Add it, take a look please

(2) I'm sorry about the confusion. Please remove the search bar from item_catalogue and unify the header with settings (for example). - **done**

(3) On the following three pages, when you scroll down and the shadow below the header appears, the shadow is slightly lower than on the other pages: guest_profile_behavior, guest_profile_history, guest_profile_items_lost. (Compare with settings, for example.) - **done**

(5) The back arrow in the upper left corner of user_profile and guest_profile are in a different position than the rest of the pages, (for example, edit_user_profile). Please unify these pages. - **done**

Please, check on mockup - pudding before the first title have to be 24px (this block was moved up before). - this is same paddings as on all other pages. We try to unify them, so if you want to change this padding, we need to change it everywhere (and I think it's better  not to do this. Hard to unify so much files, I can easy miss something)

(6) Adjust the headers on reports_operations and reports_behavior to comply with the style in Figma. To me the most obvious problem is the date selection link is too close to the content below it. - **done**

(7) Unify titles to 10 px weight 500 on the following pages: - **done**

(8) Confirm there is 16 px padding below the search bar on the following pages: - **done**
