### ISSUE TITLE
Distribution modal update

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#74]
@AnKar112 
We are changing the icons on the distribution modal on the giving page according to the details [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575). 

I believe the only change are the icons on the left column. The function here does not matter for the design - we just need the template updated.

![Screenshot 2022-03-23 101702](https://user-images.githubusercontent.com/13606352/159610782-125f7b3b-4588-4bdf-a9c1-c32ea651986f.png)

**Comment by AnKar112** [comment]
1. About blank card (I noticed this comment https://i.imgur.com/imcOc3k.jpg ) - I made this card (it has class 'blank'), it just not displaying. You can easily turn it when you need, just off "display: none;" 
https://i.imgur.com/k0qD9db.jpg
2. New icons - done

**Comment by d33pspace** [comment]
@AnKar112 
These changes look great and thank you for pointing out the "blank" card! Closing this issue.

**Comment by d33pspace** [comment]
@AnKar112 
I'm sorry one more thing here. 

In [your template](https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html), there is no example of the row with the garbage can on it, like the last row in the Figma sample above.

**Comment by edwazhao** [comment]
@AnKar112 
Could you please make an example in the `give page` of  `just off "display: none;"` you mentioned above, since the current issue could be difficult to track in the future, it is better to have the example available in the template.

BTW, to make it easy for you there is no need to fill all the Given column, because some of them could be empty. For the modal dialog, just some valuable examples is totally fine.

**Comment by d33pspace** [comment]
@AnKar112 
Summary here:

On give_page distribution pop-up modal, please provide examples of a row with a garbage can on it (according to design in [Figma](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575), and a row with "display: none;"
